GET http://localhost:8080/api/web/etudiant
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJldHVkaWFudDFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDg1NDM5ODYsImV4cCI6MTc0ODYzMDM4Nn0.iBV5nNzrFNNEamCpFFxqe-NKv2FiNROwO5bfZhW687I

###
POST http://localhost:8080/api/web/etudiant
Accept: application/json
Content-Type: application/json
Authorization: Basic dXNlcjplM2NlNDQwZi0wMjg3LTQwZWEtYTdmZi02YzlkM2VmNWVjYzM=

{
  "nom": "Test",
  "prenom": "User",
  "email": "test@example.com",
  "password": "password123",
  "role": "ADMIN"
}


###
POST http://localhost:8080/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "etudiant1@example.com",
    "password": "password1"
}

###
GET http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJldHVkaWFudDFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDg1NDYxNjEsImV4cCI6MTc0ODYzMjU2MX0.k271BzLFk5d8AJohNAy0UXi6e3z5Luafvc6f_plZC80