package ism.groupe9.gestion_absence.mobile.controllers.impl;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
import java.util.Map;

import org.springframework.http.ResponseEntity;

import ism.groupe9.gestion_absence.data.entities.Justification;
import ism.groupe9.gestion_absence.web.controllers.JustificationController;

public class JustificationControllerImpl implements JustificationController {

  @Override
  public ResponseEntity<Map<String, Object>> getAll() {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'getAll'");
  }

  @Override
  public ResponseEntity<Map<String, Object>> getByAbsenceId(String absenceId) {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'getByAbsenceId'");
  }

  @Override
  public ResponseEntity<Map<String, Object>> validationJustification(String id, Justification justification) {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'validationJustification'");
  }

}
