package ism.groupe9.gestion_absence.mobile.controllers.impl;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
import java.util.Map;

import org.springframework.http.ResponseEntity;

import ism.groupe9.gestion_absence.mobile.controllers.MobileJustificationController;

public class MobileJustificationControllerImpl implements MobileJustificationController {

  @Override
  public ResponseEntity<Map<String, Object>> getByAbsenceId(String absenceId) {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'getByAbsenceId'");
  }

}
